version: 2

models:
  - name: dim_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: dim_products
    columns:  # Ensure proper indentation before "- name"
      - name: product_id
        tests:
          - unique
          - not_null

  - name: fct_orders
    columns:
      - name: order_id
        tests:
          - not_null
      - name: order_status
        tests: 
          - not_null
      - name: unite_price
        tests:
          - positive_value

